/* tslint:disable */
/* eslint-disable */
/**
 * Conovel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface EvaluateSentence
 */
export interface EvaluateSentence {
    /**
     * 評価対象の投稿のID
     * @type {number}
     * @memberof EvaluateSentence
     */
    'sentence_id'?: number;
    /**
     * 評価の種類
     * @type {string}
     * @memberof EvaluateSentence
     */
    'evaluation'?: EvaluateSentenceEvaluationEnum;
}

export const EvaluateSentenceEvaluationEnum = {
    Good: 'good',
    Bad: 'bad',
    Stay: 'stay'
} as const;

export type EvaluateSentenceEvaluationEnum = typeof EvaluateSentenceEvaluationEnum[keyof typeof EvaluateSentenceEvaluationEnum];

/**
 * 
 * @export
 * @interface NovelDetail
 */
export interface NovelDetail {
    /**
     * 小説の一意のid（この値は他の小説と重複しない必要があります）
     * @type {number}
     * @memberof NovelDetail
     */
    'title_id'?: number;
    /**
     * 小説のタイトル
     * @type {string}
     * @memberof NovelDetail
     */
    'title'?: string;
    /**
     * 名言・印象に残るシーン
     * @type {string}
     * @memberof NovelDetail
     */
    'famous_sentence_text'?: string;
    /**
     * 小説の作者のid
     * @type {number}
     * @memberof NovelDetail
     */
    'author_user_id'?: number;
    /**
     * 小説の作者のペンネーム
     * @type {string}
     * @memberof NovelDetail
     */
    'author_user_name'?: string;
    /**
     * 小説の作者のアイコン画像のurl
     * @type {string}
     * @memberof NovelDetail
     */
    'profile_icon_image'?: string;
    /**
     * 小説のジャンル
     * @type {Array<string>}
     * @memberof NovelDetail
     */
    'title_genres'?: Array<string>;
    /**
     * 新着小説かどうか
     * @type {boolean}
     * @memberof NovelDetail
     */
    'is_new'?: boolean;
    /**
     * 人気小説かどうか
     * @type {boolean}
     * @memberof NovelDetail
     */
    'is_famous'?: boolean;
    /**
     * 小説の閲覧数
     * @type {number}
     * @memberof NovelDetail
     */
    'view_count'?: number;
    /**
     * 小説のGood評価の数
     * @type {number}
     * @memberof NovelDetail
     */
    'evaluation_good_count'?: number;
    /**
     * 小説の作成日時
     * @type {string}
     * @memberof NovelDetail
     */
    'created_at'?: string;
    /**
     * 小説の修正日時
     * @type {string}
     * @memberof NovelDetail
     */
    'updated_at'?: string;
    /**
     * 小説の紹介文
     * @type {string}
     * @memberof NovelDetail
     */
    'main_copy'?: string;
    /**
     * 小説に投稿された投稿の数
     * @type {number}
     * @memberof NovelDetail
     */
    'sentence_user_count'?: number;
    /**
     * 小説に投稿された投稿の階層数
     * @type {number}
     * @memberof NovelDetail
     */
    'sentence_hierarchy_count'?: number;
    /**
     * 小説を読んだユーザーの数
     * @type {number}
     * @memberof NovelDetail
     */
    'reader_count'?: number;
    /**
     * 小説のあらすじ
     * @type {string}
     * @memberof NovelDetail
     */
    'overview'?: string;
}
/**
 * 
 * @export
 * @interface NovelListItem
 */
export interface NovelListItem {
    /**
     * 小説の一意のid（この値は他の小説と重複しない必要があります）
     * @type {number}
     * @memberof NovelListItem
     */
    'title_id'?: number;
    /**
     * 小説のタイトル
     * @type {string}
     * @memberof NovelListItem
     */
    'title'?: string;
    /**
     * 名言・印象に残るシーン
     * @type {string}
     * @memberof NovelListItem
     */
    'famous_sentence_text'?: string;
    /**
     * 小説の作者のid
     * @type {number}
     * @memberof NovelListItem
     */
    'author_user_id'?: number;
    /**
     * 小説の作者のペンネーム
     * @type {string}
     * @memberof NovelListItem
     */
    'author_user_name'?: string;
    /**
     * 小説の作者のアイコン画像のurl
     * @type {string}
     * @memberof NovelListItem
     */
    'profile_icon_image'?: string;
    /**
     * 小説のジャンル
     * @type {Array<string>}
     * @memberof NovelListItem
     */
    'title_genres'?: Array<string>;
    /**
     * 新着小説かどうか
     * @type {boolean}
     * @memberof NovelListItem
     */
    'is_new'?: boolean;
    /**
     * 人気小説かどうか
     * @type {boolean}
     * @memberof NovelListItem
     */
    'is_famous'?: boolean;
    /**
     * 小説の閲覧数
     * @type {number}
     * @memberof NovelListItem
     */
    'view_count'?: number;
    /**
     * 小説のGood評価の数
     * @type {number}
     * @memberof NovelListItem
     */
    'evaluation_good_count'?: number;
    /**
     * 小説の作成日時
     * @type {string}
     * @memberof NovelListItem
     */
    'created_at'?: string;
    /**
     * 小説の修正日時
     * @type {string}
     * @memberof NovelListItem
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface PostSentence
 */
export interface PostSentence {
    /**
     * 親投稿のid
     * @type {number}
     * @memberof PostSentence
     */
    'parent_sentence_id'?: number;
    /**
     * 親投稿の修正日時(投稿中の親投稿の更新有無を確認するため)
     * @type {string}
     * @memberof PostSentence
     */
    'parent_updated_at'?: string;
    /**
     * 新投稿の本文テキスト
     * @type {string}
     * @memberof PostSentence
     */
    'sentence'?: string;
}
/**
 * 
 * @export
 * @interface Sentence
 */
export interface Sentence {
    /**
     * 投稿の一意のid（この値は他の投稿と重複しない必要があります）
     * @type {number}
     * @memberof Sentence
     */
    'sentence_id'?: number;
    /**
     * 投稿の本文テキスト
     * @type {string}
     * @memberof Sentence
     */
    'sentence'?: string;
    /**
     * 投稿ユーザーのid
     * @type {number}
     * @memberof Sentence
     */
    'sentence_user_id'?: number;
    /**
     * 投稿ユーザーのペンネーム
     * @type {string}
     * @memberof Sentence
     */
    'sentence_user_name'?: string;
    /**
     * 投稿ユーザーアイコン画像のurl
     * @type {string}
     * @memberof Sentence
     */
    'profile_icon_image'?: string;
    /**
     * 投稿に対するGood評価の数
     * @type {number}
     * @memberof Sentence
     */
    'evaluation_good_count'?: number;
    /**
     * 投稿に対するStay評価の数
     * @type {number}
     * @memberof Sentence
     */
    'evaluation_stay_count'?: number;
    /**
     * 投稿日時
     * @type {string}
     * @memberof Sentence
     */
    'created_at'?: string;
    /**
     * 修正日時
     * @type {string}
     * @memberof Sentence
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
    /**
     * ユーザーのペンネーム
     * @type {string}
     * @memberof UpdateUser
     */
    'user_name'?: string;
    /**
     * ユーザーのニックネーム
     * @type {string}
     * @memberof UpdateUser
     */
    'nick_name'?: string;
    /**
     * 匿名設定
     * @type {boolean}
     * @memberof UpdateUser
     */
    'is_anonymous'?: boolean;
    /**
     * ユーザーアイコン画像のurl
     * @type {string}
     * @memberof UpdateUser
     */
    'profile_icon_image'?: string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * ユーザーの一意のid
     * @type {number}
     * @memberof User
     */
    'user_id'?: number;
    /**
     * ユーザーのペンネーム
     * @type {string}
     * @memberof User
     */
    'user_name'?: string;
    /**
     * ユーザーのニックネーム
     * @type {string}
     * @memberof User
     */
    'nick_name'?: string;
    /**
     * ユーザーアイコン画像のurl
     * @type {string}
     * @memberof User
     */
    'profile_icon_image'?: string;
    /**
     * Good評価の数
     * @type {number}
     * @memberof User
     */
    'evaluation_good_count'?: number;
    /**
     * ユーザーの作成日時
     * @type {string}
     * @memberof User
     */
    'created_at'?: string;
    /**
     * ユーザーの修正日時
     * @type {string}
     * @memberof User
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface ViewEvaluation
 */
export interface ViewEvaluation {
    /**
     * 評価対象の投稿のID
     * @type {number}
     * @memberof ViewEvaluation
     */
    'sentence_id'?: number;
    /**
     * Good評価の数
     * @type {number}
     * @memberof ViewEvaluation
     */
    'evaluation_good_count'?: number;
    /**
     * Stay評価の数
     * @type {number}
     * @memberof ViewEvaluation
     */
    'evaluation_stay_count'?: number;
}
/**
 * 
 * @export
 * @interface ViewMeUser
 */
export interface ViewMeUser {
    /**
     * ユーザーの一意のid
     * @type {number}
     * @memberof ViewMeUser
     */
    'user_id'?: number;
    /**
     * ユーザーのペンネーム
     * @type {string}
     * @memberof ViewMeUser
     */
    'user_name'?: string;
    /**
     * ユーザーのニックネーム
     * @type {string}
     * @memberof ViewMeUser
     */
    'nick_name'?: string;
    /**
     * ユーザーアイコン画像のurl
     * @type {string}
     * @memberof ViewMeUser
     */
    'profile_icon_image'?: string;
    /**
     * Good評価の数
     * @type {number}
     * @memberof ViewMeUser
     */
    'evaluation_good_count'?: number;
    /**
     * ユーザーの作成日時
     * @type {string}
     * @memberof ViewMeUser
     */
    'created_at'?: string;
    /**
     * ユーザーの修正日時
     * @type {string}
     * @memberof ViewMeUser
     */
    'updated_at'?: string;
    /**
     * ユーザーの生年月（YYYY/MM）
     * @type {string}
     * @memberof ViewMeUser
     */
    'birth_year_and_month'?: string;
    /**
     * 匿名設定
     * @type {boolean}
     * @memberof ViewMeUser
     */
    'is_anonymous'?: boolean;
}
/**
 * 
 * @export
 * @interface ViewSentence
 */
export interface ViewSentence {
    /**
     * 
     * @type {Sentence}
     * @memberof ViewSentence
     */
    'main'?: Sentence;
    /**
     * 
     * @type {Sentence}
     * @memberof ViewSentence
     */
    'parent'?: Sentence;
    /**
     * 
     * @type {Array<Sentence>}
     * @memberof ViewSentence
     */
    'parallels'?: Array<Sentence>;
    /**
     * 
     * @type {Array<Sentence>}
     * @memberof ViewSentence
     */
    'children'?: Array<Sentence>;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ログアウト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logOut: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ログアウト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logOut(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logOut(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.logOut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary ログアウト
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logOut(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.logOut(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public logOut(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).logOut(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EvaluationsApi - axios parameter creator
 * @export
 */
export const EvaluationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 投稿に対する評価を追加
         * @param {EvaluateSentence} evaluateSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        evaluateSentence: async (evaluateSentence: EvaluateSentence, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'evaluateSentence' is not null or undefined
            assertParamExists('evaluateSentence', 'evaluateSentence', evaluateSentence)
            const localVarPath = `/evaluations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(evaluateSentence, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EvaluationsApi - functional programming interface
 * @export
 */
export const EvaluationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EvaluationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 投稿に対する評価を追加
         * @param {EvaluateSentence} evaluateSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async evaluateSentence(evaluateSentence: EvaluateSentence, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewEvaluation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.evaluateSentence(evaluateSentence, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EvaluationsApi.evaluateSentence']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EvaluationsApi - factory interface
 * @export
 */
export const EvaluationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EvaluationsApiFp(configuration)
    return {
        /**
         * 
         * @summary 投稿に対する評価を追加
         * @param {EvaluateSentence} evaluateSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        evaluateSentence(evaluateSentence: EvaluateSentence, options?: RawAxiosRequestConfig): AxiosPromise<ViewEvaluation> {
            return localVarFp.evaluateSentence(evaluateSentence, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EvaluationsApi - object-oriented interface
 * @export
 * @class EvaluationsApi
 * @extends {BaseAPI}
 */
export class EvaluationsApi extends BaseAPI {
    /**
     * 
     * @summary 投稿に対する評価を追加
     * @param {EvaluateSentence} evaluateSentence 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EvaluationsApi
     */
    public evaluateSentence(evaluateSentence: EvaluateSentence, options?: RawAxiosRequestConfig) {
        return EvaluationsApiFp(this.configuration).evaluateSentence(evaluateSentence, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NovelsApi - axios parameter creator
 * @export
 */
export const NovelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary IDで小説の概要を取得
         * @param {number} titleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovelById: async (titleId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'titleId' is not null or undefined
            assertParamExists('getNovelById', 'titleId', titleId)
            const localVarPath = `/novels/{title_id}`
                .replace(`{${"title_id"}}`, encodeURIComponent(String(titleId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovels: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/novels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NovelsApi - functional programming interface
 * @export
 */
export const NovelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NovelsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary IDで小説の概要を取得
         * @param {number} titleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNovelById(titleId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NovelDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNovelById(titleId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NovelsApi.getNovelById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNovels(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NovelListItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNovels(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NovelsApi.getNovels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NovelsApi - factory interface
 * @export
 */
export const NovelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NovelsApiFp(configuration)
    return {
        /**
         * 
         * @summary IDで小説の概要を取得
         * @param {number} titleId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovelById(titleId: number, options?: RawAxiosRequestConfig): AxiosPromise<NovelDetail> {
            return localVarFp.getNovelById(titleId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovels(options?: RawAxiosRequestConfig): AxiosPromise<Array<NovelListItem>> {
            return localVarFp.getNovels(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NovelsApi - object-oriented interface
 * @export
 * @class NovelsApi
 * @extends {BaseAPI}
 */
export class NovelsApi extends BaseAPI {
    /**
     * 
     * @summary IDで小説の概要を取得
     * @param {number} titleId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NovelsApi
     */
    public getNovelById(titleId: number, options?: RawAxiosRequestConfig) {
        return NovelsApiFp(this.configuration).getNovelById(titleId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 小説リストを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NovelsApi
     */
    public getNovels(options?: RawAxiosRequestConfig) {
        return NovelsApiFp(this.configuration).getNovels(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SentencesApi - axios parameter creator
 * @export
 */
export const SentencesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary IDで投稿を取得
         * @param {number} sentenceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSentenceById: async (sentenceId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sentenceId' is not null or undefined
            assertParamExists('getSentenceById', 'sentenceId', sentenceId)
            const localVarPath = `/sentences/{sentence_id}`
                .replace(`{${"sentence_id"}}`, encodeURIComponent(String(sentenceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary メイン投稿の続きの新規投稿を作成
         * @param {PostSentence} postSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSentence: async (postSentence: PostSentence, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postSentence' is not null or undefined
            assertParamExists('postSentence', 'postSentence', postSentence)
            const localVarPath = `/sentences`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postSentence, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SentencesApi - functional programming interface
 * @export
 */
export const SentencesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SentencesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary IDで投稿を取得
         * @param {number} sentenceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSentenceById(sentenceId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSentenceById(sentenceId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SentencesApi.getSentenceById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary メイン投稿の続きの新規投稿を作成
         * @param {PostSentence} postSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSentence(postSentence: PostSentence, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSentence(postSentence, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SentencesApi.postSentence']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SentencesApi - factory interface
 * @export
 */
export const SentencesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SentencesApiFp(configuration)
    return {
        /**
         * 
         * @summary IDで投稿を取得
         * @param {number} sentenceId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSentenceById(sentenceId: number, options?: RawAxiosRequestConfig): AxiosPromise<ViewSentence> {
            return localVarFp.getSentenceById(sentenceId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary メイン投稿の続きの新規投稿を作成
         * @param {PostSentence} postSentence 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSentence(postSentence: PostSentence, options?: RawAxiosRequestConfig): AxiosPromise<ViewSentence> {
            return localVarFp.postSentence(postSentence, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SentencesApi - object-oriented interface
 * @export
 * @class SentencesApi
 * @extends {BaseAPI}
 */
export class SentencesApi extends BaseAPI {
    /**
     * 
     * @summary IDで投稿を取得
     * @param {number} sentenceId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SentencesApi
     */
    public getSentenceById(sentenceId: number, options?: RawAxiosRequestConfig) {
        return SentencesApiFp(this.configuration).getSentenceById(sentenceId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary メイン投稿の続きの新規投稿を作成
     * @param {PostSentence} postSentence 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SentencesApi
     */
    public postSentence(postSentence: PostSentence, options?: RawAxiosRequestConfig) {
        return SentencesApiFp(this.configuration).postSentence(postSentence, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 自分自身のユーザーアカウントを削除（論理削除）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserByMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/delete`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ユーザーが投稿している小説リストを取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovelsByUserId: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getNovelsByUserId', 'userId', userId)
            const localVarPath = `/users/{user_id}/posted_novels`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary IDで自分以外のユーザーアカウント情報を取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById: async (userId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUserById', 'userId', userId)
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 自分自身が閲覧している小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getViewedNovelsByMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me/viewed_novels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を更新
         * @param {UpdateUser} updateUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserByMe: async (updateUser: UpdateUser, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUser' is not null or undefined
            assertParamExists('updateUserByMe', 'updateUser', updateUser)
            const localVarPath = `/users/me/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 自分自身のユーザーアカウントを削除（論理削除）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUserByMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUserByMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.deleteUserByMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ユーザーが投稿している小説リストを取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNovelsByUserId(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NovelListItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNovelsByUserId(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getNovelsByUserId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary IDで自分以外のユーザーアカウント情報を取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserById(userId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserByMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewMeUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserByMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUserByMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 自分自身が閲覧している小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getViewedNovelsByMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<NovelListItem>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getViewedNovelsByMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getViewedNovelsByMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を更新
         * @param {UpdateUser} updateUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserByMe(updateUser: UpdateUser, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserByMe(updateUser, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateUserByMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary 自分自身のユーザーアカウントを削除（論理削除）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteUserByMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ユーザーが投稿している小説リストを取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNovelsByUserId(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<NovelListItem>> {
            return localVarFp.getNovelsByUserId(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary IDで自分以外のユーザーアカウント情報を取得
         * @param {number} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserById(userId: number, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getUserById(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<ViewMeUser> {
            return localVarFp.getUserByMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 自分自身が閲覧している小説リストを取得
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getViewedNovelsByMe(options?: RawAxiosRequestConfig): AxiosPromise<Array<NovelListItem>> {
            return localVarFp.getViewedNovelsByMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 自分自身のユーザーアカウント情報を更新
         * @param {UpdateUser} updateUser 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserByMe(updateUser: UpdateUser, options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.updateUserByMe(updateUser, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary 自分自身のユーザーアカウントを削除（論理削除）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public deleteUserByMe(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).deleteUserByMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ユーザーが投稿している小説リストを取得
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getNovelsByUserId(userId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getNovelsByUserId(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary IDで自分以外のユーザーアカウント情報を取得
     * @param {number} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserById(userId: number, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserById(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 自分自身のユーザーアカウント情報を取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getUserByMe(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUserByMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 自分自身が閲覧している小説リストを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getViewedNovelsByMe(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getViewedNovelsByMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 自分自身のユーザーアカウント情報を更新
     * @param {UpdateUser} updateUser 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public updateUserByMe(updateUser: UpdateUser, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateUserByMe(updateUser, options).then((request) => request(this.axios, this.basePath));
    }
}



