/**
 * Conovel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import type { RequestArgs } from './base';
import { BaseAPI } from './base';
export declare const createRefreshTokenRequest: (
  configuration: Configuration | undefined,
  axios: AxiosInstance,
  basePath: string,
  options?: RawAxiosRequestConfig,
) => () => Promise<import('axios').AxiosResponse<void, any, {}>>;
/**
 *
 * @export
 * @interface ConflictSentence
 */
export interface ConflictSentence {
  /**
   *
   * @type {ErrorResponseError}
   * @memberof ConflictSentence
   */
  error?: ErrorResponseError;
  /**
   *
   * @type {Sentence}
   * @memberof ConflictSentence
   */
  main?: Sentence;
  /**
   *
   * @type {Sentence}
   * @memberof ConflictSentence
   */
  parent?: Sentence;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ConflictSentence
   */
  parallels?: Array<Sentence>;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ConflictSentence
   */
  children?: Array<Sentence>;
}
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {ErrorResponseError}
   * @memberof ErrorResponse
   */
  error?: ErrorResponseError;
}
/**
 *
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
  /**
   * エラーコード
   * @type {number}
   * @memberof ErrorResponseError
   */
  code?: number;
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof ErrorResponseError
   */
  message?: string;
}
/**
 *
 * @export
 * @interface EvaluateSentence
 */
export interface EvaluateSentence {
  /**
   * 評価対象の投稿のID（必須）
   * @type {number}
   * @memberof EvaluateSentence
   */
  sentenceId: number;
  /**
   * 評価の種類（必須）
   * @type {string}
   * @memberof EvaluateSentence
   */
  evaluation: EvaluateSentenceEvaluationEnum;
}
export declare const EvaluateSentenceEvaluationEnum: {
  readonly Good: 'good';
  readonly Bad: 'bad';
  readonly Stay: 'stay';
};
export type EvaluateSentenceEvaluationEnum =
  (typeof EvaluateSentenceEvaluationEnum)[keyof typeof EvaluateSentenceEvaluationEnum];
/**
 *
 * @export
 * @interface NovelDetail
 */
export interface NovelDetail {
  /**
   * 小説の一意のid（この値は他の小説と重複しない必要があります）
   * @type {number}
   * @memberof NovelDetail
   */
  titleId?: number;
  /**
   * 小説のタイトル
   * @type {string}
   * @memberof NovelDetail
   */
  title?: string;
  /**
   * 名言・印象に残るシーン
   * @type {string}
   * @memberof NovelDetail
   */
  famousSentenceText?: string;
  /**
   * 小説の作者のid
   * @type {number}
   * @memberof NovelDetail
   */
  authorUserId?: number;
  /**
   * 小説の作者のペンネーム
   * @type {string}
   * @memberof NovelDetail
   */
  authorPenName?: string;
  /**
   * 小説の作者のアイコン画像のurl
   * @type {string}
   * @memberof NovelDetail
   */
  profileIconImage?: string;
  /**
   * 小説のジャンル
   * @type {Array<string>}
   * @memberof NovelDetail
   */
  titleGenres?: Array<string>;
  /**
   * 新着小説かどうか
   * @type {boolean}
   * @memberof NovelDetail
   */
  isNew?: boolean;
  /**
   * 人気小説かどうか
   * @type {boolean}
   * @memberof NovelDetail
   */
  isFamous?: boolean;
  /**
   * 小説の閲覧数
   * @type {number}
   * @memberof NovelDetail
   */
  viewCount?: number;
  /**
   * 小説のGood評価の数
   * @type {number}
   * @memberof NovelDetail
   */
  evaluationGoodCount?: number;
  /**
   * 小説の作成日時
   * @type {string}
   * @memberof NovelDetail
   */
  createdAt?: string;
  /**
   * 小説の修正日時
   * @type {string}
   * @memberof NovelDetail
   */
  updatedAt?: string;
  /**
   * 小説の紹介文
   * @type {string}
   * @memberof NovelDetail
   */
  mainCopy?: string;
  /**
   * 小説に投稿している投稿者の数
   * @type {number}
   * @memberof NovelDetail
   */
  sentenceUserCount?: number;
  /**
   * 小説に投稿された投稿の階層数
   * @type {number}
   * @memberof NovelDetail
   */
  sentenceHierarchyCount?: number;
  /**
   * 小説を読んだユーザーの数
   * @type {number}
   * @memberof NovelDetail
   */
  readerCount?: number;
  /**
   * 小説のあらすじ
   * @type {string}
   * @memberof NovelDetail
   */
  overview?: string;
}
/**
 *
 * @export
 * @interface NovelListItem
 */
export interface NovelListItem {
  /**
   * 小説の一意のid（この値は他の小説と重複しない必要があります）
   * @type {number}
   * @memberof NovelListItem
   */
  titleId?: number;
  /**
   * 小説のタイトル
   * @type {string}
   * @memberof NovelListItem
   */
  title?: string;
  /**
   * 名言・印象に残るシーン
   * @type {string}
   * @memberof NovelListItem
   */
  famousSentenceText?: string;
  /**
   * 小説の作者のid
   * @type {number}
   * @memberof NovelListItem
   */
  authorUserId?: number;
  /**
   * 小説の作者のペンネーム
   * @type {string}
   * @memberof NovelListItem
   */
  authorPenName?: string;
  /**
   * 小説の作者のアイコン画像のurl
   * @type {string}
   * @memberof NovelListItem
   */
  profileIconImage?: string;
  /**
   * 小説のジャンル
   * @type {Array<string>}
   * @memberof NovelListItem
   */
  titleGenres?: Array<string>;
  /**
   * 新着小説かどうか
   * @type {boolean}
   * @memberof NovelListItem
   */
  isNew?: boolean;
  /**
   * 人気小説かどうか
   * @type {boolean}
   * @memberof NovelListItem
   */
  isFamous?: boolean;
  /**
   * 小説の閲覧数
   * @type {number}
   * @memberof NovelListItem
   */
  viewCount?: number;
  /**
   * 小説のGood評価の数
   * @type {number}
   * @memberof NovelListItem
   */
  evaluationGoodCount?: number;
  /**
   * 小説の作成日時
   * @type {string}
   * @memberof NovelListItem
   */
  createdAt?: string;
  /**
   * 小説の修正日時
   * @type {string}
   * @memberof NovelListItem
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface PostSentence
 */
export interface PostSentence {
  /**
   * 親投稿のid（必須）
   * @type {number}
   * @memberof PostSentence
   */
  parentSentenceId: number;
  /**
   * 親投稿の修正日時(投稿中の親投稿の更新有無を確認するため)（必須）
   * @type {string}
   * @memberof PostSentence
   */
  parentUpdatedAt: string;
  /**
   * 新投稿の本文テキスト（必須）
   * @type {string}
   * @memberof PostSentence
   */
  sentence: string;
}
/**
 *
 * @export
 * @interface Sentence
 */
export interface Sentence {
  /**
   * 投稿の一意のid（この値は他の投稿と重複しない必要があります）
   * @type {number}
   * @memberof Sentence
   */
  sentenceId?: number;
  /**
   * 投稿の本文テキスト
   * @type {string}
   * @memberof Sentence
   */
  sentence?: string;
  /**
   * 投稿ユーザーのid
   * @type {number}
   * @memberof Sentence
   */
  sentenceUserId?: number;
  /**
   * 投稿ユーザーのペンネーム
   * @type {string}
   * @memberof Sentence
   */
  sentencePenName?: string;
  /**
   * 投稿ユーザーアイコン画像のurl
   * @type {string}
   * @memberof Sentence
   */
  profileIconImage?: string;
  /**
   * 投稿に対するGood評価の数
   * @type {number}
   * @memberof Sentence
   */
  evaluationGoodCount?: number;
  /**
   * 投稿に対するStay評価の数
   * @type {number}
   * @memberof Sentence
   */
  evaluationStayCount?: number;
  /**
   * 投稿日時
   * @type {string}
   * @memberof Sentence
   */
  createdAt?: string;
  /**
   * 修正日時
   * @type {string}
   * @memberof Sentence
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
  /**
   * ユーザーのペンネーム（必須）
   * @type {string}
   * @memberof UpdateUser
   */
  penName: string;
  /**
   * ユーザーのニックネーム（必須）
   * @type {string}
   * @memberof UpdateUser
   */
  nickName: string;
  /**
   * 匿名設定（必須）
   * @type {boolean}
   * @memberof UpdateUser
   */
  isAnonymous: boolean;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof UpdateUser
   */
  profileIconImage?: string;
  /**
   * ユーザーの生年月（YYYY/MM）（必須）
   * @type {string}
   * @memberof UpdateUser
   */
  birthYm: string;
  /**
   * 同意した利用規約のバージョン（必須）
   * @type {number}
   * @memberof UpdateUser
   */
  agreedTermsVersion: number;
  /**
   * ユーザーの備考
   * @type {string}
   * @memberof UpdateUser
   */
  remarks?: string;
}
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * ユーザーの一意のid
   * @type {number}
   * @memberof User
   */
  userId?: number;
  /**
   * ユーザーのペンネーム
   * @type {string}
   * @memberof User
   */
  penName?: string;
  /**
   * ユーザーのニックネーム
   * @type {string}
   * @memberof User
   */
  nickName?: string;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof User
   */
  profileIconImage?: string;
  /**
   * Good評価の数
   * @type {number}
   * @memberof User
   */
  evaluationGoodCount?: number;
  /**
   * ユーザーの作成日時
   * @type {string}
   * @memberof User
   */
  createdAt?: string;
  /**
   * ユーザーの修正日時
   * @type {string}
   * @memberof User
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface ViewEvaluation
 */
export interface ViewEvaluation {
  /**
   * 評価対象の投稿のID
   * @type {number}
   * @memberof ViewEvaluation
   */
  sentenceId?: number;
  /**
   * Good評価の数
   * @type {number}
   * @memberof ViewEvaluation
   */
  evaluationGoodCount?: number;
  /**
   * Stay評価の数
   * @type {number}
   * @memberof ViewEvaluation
   */
  evaluationStayCount?: number;
}
/**
 *
 * @export
 * @interface ViewMeUser
 */
export interface ViewMeUser {
  /**
   * ユーザーの一意のid
   * @type {number}
   * @memberof ViewMeUser
   */
  userId?: number;
  /**
   * ユーザーのペンネーム
   * @type {string}
   * @memberof ViewMeUser
   */
  penName?: string;
  /**
   * ユーザーのニックネーム
   * @type {string}
   * @memberof ViewMeUser
   */
  nickName?: string;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof ViewMeUser
   */
  profileIconImage?: string;
  /**
   * Good評価の数
   * @type {number}
   * @memberof ViewMeUser
   */
  evaluationGoodCount?: number;
  /**
   * ユーザーの作成日時
   * @type {string}
   * @memberof ViewMeUser
   */
  createdAt?: string;
  /**
   * ユーザーの修正日時
   * @type {string}
   * @memberof ViewMeUser
   */
  updatedAt?: string;
  /**
   * ユーザーの生年月（YYYY/MM）
   * @type {string}
   * @memberof ViewMeUser
   */
  birthYearAndMonth?: string;
  /**
   * 匿名設定
   * @type {boolean}
   * @memberof ViewMeUser
   */
  isAnonymous?: boolean;
}
/**
 *
 * @export
 * @interface ViewSentence
 */
export interface ViewSentence {
  /**
   *
   * @type {Sentence}
   * @memberof ViewSentence
   */
  main?: Sentence;
  /**
   *
   * @type {Sentence}
   * @memberof ViewSentence
   */
  parent?: Sentence;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ViewSentence
   */
  parallels?: Array<Sentence>;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ViewSentence
   */
  children?: Array<Sentence>;
}
/**
 * AuthApi - axios parameter creator
 * @export
 */
export declare const AuthApiAxiosParamCreator: (
  configuration?: Configuration,
) => {
  /**
   *
   * @summary ログアウト
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  logOut: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
  /**
   *
   * @summary トークンのリフレッシュ（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  refreshToken: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AuthApi - functional programming interface
 * @export
 */
export declare const AuthApiFp: (configuration?: Configuration) => {
  /**
   *
   * @summary ログアウト
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  logOut(
    options?: RawAxiosRequestConfig,
  ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
  /**
   *
   * @summary トークンのリフレッシュ（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  refreshToken(
    options?: RawAxiosRequestConfig,
  ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
};
/**
 * AuthApi - factory interface
 * @export
 */
export declare const AuthApiFactory: (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) => {
  /**
   *
   * @summary ログアウト
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  logOut(options?: RawAxiosRequestConfig): AxiosPromise<void>;
  /**
   *
   * @summary トークンのリフレッシュ（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  refreshToken(options?: RawAxiosRequestConfig): AxiosPromise<void>;
};
/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export declare class AuthApi extends BaseAPI {
  /**
   *
   * @summary ログアウト
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  logOut(
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<void, any, {}>>;
  /**
   *
   * @summary トークンのリフレッシュ（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  refreshToken(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<void, any, {}> | null | undefined>;
}
/**
 * EvaluationsApi - axios parameter creator
 * @export
 */
export declare const EvaluationsApiAxiosParamCreator: (
  configuration?: Configuration,
) => {
  /**
   *
   * @summary 投稿に対する評価を追加（認証あり）
   * @param {EvaluateSentence} evaluateSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  evaluateSentence: (
    evaluateSentence: EvaluateSentence,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
};
/**
 * EvaluationsApi - functional programming interface
 * @export
 */
export declare const EvaluationsApiFp: (configuration?: Configuration) => {
  /**
   *
   * @summary 投稿に対する評価を追加（認証あり）
   * @param {EvaluateSentence} evaluateSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  evaluateSentence(
    evaluateSentence: EvaluateSentence,
    options?: RawAxiosRequestConfig,
  ): Promise<
    (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewEvaluation>
  >;
};
/**
 * EvaluationsApi - factory interface
 * @export
 */
export declare const EvaluationsApiFactory: (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) => {
  /**
   *
   * @summary 投稿に対する評価を追加（認証あり）
   * @param {EvaluateSentence} evaluateSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  evaluateSentence(
    evaluateSentence: EvaluateSentence,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ViewEvaluation>;
};
/**
 * EvaluationsApi - object-oriented interface
 * @export
 * @class EvaluationsApi
 * @extends {BaseAPI}
 */
export declare class EvaluationsApi extends BaseAPI {
  /**
   *
   * @summary 投稿に対する評価を追加（認証あり）
   * @param {EvaluateSentence} evaluateSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EvaluationsApi
   */
  evaluateSentence(
    evaluateSentence: EvaluateSentence,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<
    import('axios').AxiosResponse<ViewEvaluation, any, {}> | null | undefined
  >;
}
/**
 * NovelsApi - axios parameter creator
 * @export
 */
export declare const NovelsApiAxiosParamCreator: (
  configuration?: Configuration,
) => {
  /**
   *
   * @summary IDで小説の概要を取得
   * @param {number} titleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelById: (
    titleId: number,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
  /**
   *
   * @summary 小説リストを取得
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovels: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * NovelsApi - functional programming interface
 * @export
 */
export declare const NovelsApiFp: (configuration?: Configuration) => {
  /**
   *
   * @summary IDで小説の概要を取得
   * @param {number} titleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelById(
    titleId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<
    (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NovelDetail>
  >;
  /**
   *
   * @summary 小説リストを取得
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovels(
    options?: RawAxiosRequestConfig,
  ): Promise<
    (
      axios?: AxiosInstance,
      basePath?: string,
    ) => AxiosPromise<Array<NovelListItem>>
  >;
};
/**
 * NovelsApi - factory interface
 * @export
 */
export declare const NovelsApiFactory: (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) => {
  /**
   *
   * @summary IDで小説の概要を取得
   * @param {number} titleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelById(
    titleId: number,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<NovelDetail>;
  /**
   *
   * @summary 小説リストを取得
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovels(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<NovelListItem>>;
};
/**
 * NovelsApi - object-oriented interface
 * @export
 * @class NovelsApi
 * @extends {BaseAPI}
 */
export declare class NovelsApi extends BaseAPI {
  /**
   *
   * @summary IDで小説の概要を取得
   * @param {number} titleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NovelsApi
   */
  getNovelById(
    titleId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<NovelDetail, any, {}>>;
  /**
   *
   * @summary 小説リストを取得
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NovelsApi
   */
  getNovels(
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<NovelListItem[], any, {}>>;
}
/**
 * SentencesApi - axios parameter creator
 * @export
 */
export declare const SentencesApiAxiosParamCreator: (
  configuration?: Configuration,
) => {
  /**
   *
   * @summary IDで投稿を取得（認証あり）
   * @param {number} sentenceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getSentenceById: (
    sentenceId: number,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
  /**
   *
   * @summary メイン投稿の続きの新規投稿を作成（認証あり）
   * @param {PostSentence} postSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  postSentence: (
    postSentence: PostSentence,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
};
/**
 * SentencesApi - functional programming interface
 * @export
 */
export declare const SentencesApiFp: (configuration?: Configuration) => {
  /**
   *
   * @summary IDで投稿を取得（認証あり）
   * @param {number} sentenceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getSentenceById(
    sentenceId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<
    (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>
  >;
  /**
   *
   * @summary メイン投稿の続きの新規投稿を作成（認証あり）
   * @param {PostSentence} postSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  postSentence(
    postSentence: PostSentence,
    options?: RawAxiosRequestConfig,
  ): Promise<
    (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>
  >;
};
/**
 * SentencesApi - factory interface
 * @export
 */
export declare const SentencesApiFactory: (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) => {
  /**
   *
   * @summary IDで投稿を取得（認証あり）
   * @param {number} sentenceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getSentenceById(
    sentenceId: number,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ViewSentence>;
  /**
   *
   * @summary メイン投稿の続きの新規投稿を作成（認証あり）
   * @param {PostSentence} postSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  postSentence(
    postSentence: PostSentence,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<ViewSentence>;
};
/**
 * SentencesApi - object-oriented interface
 * @export
 * @class SentencesApi
 * @extends {BaseAPI}
 */
export declare class SentencesApi extends BaseAPI {
  /**
   *
   * @summary IDで投稿を取得（認証あり）
   * @param {number} sentenceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SentencesApi
   */
  getSentenceById(
    sentenceId: number,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<
    import('axios').AxiosResponse<ViewSentence, any, {}> | null | undefined
  >;
  /**
   *
   * @summary メイン投稿の続きの新規投稿を作成（認証あり）
   * @param {PostSentence} postSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SentencesApi
   */
  postSentence(
    postSentence: PostSentence,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<
    import('axios').AxiosResponse<ViewSentence, any, {}> | null | undefined
  >;
}
/**
 * UsersApi - axios parameter creator
 * @export
 */
export declare const UsersApiAxiosParamCreator: (
  configuration?: Configuration,
) => {
  /**
   *
   * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteUserByMe: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
  /**
   *
   * @summary ユーザーが投稿している小説リストを取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelsByUserId: (
    userId: number,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
  /**
   *
   * @summary IDで自分以外のユーザーアカウント情報を取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserById: (
    userId: number,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserByMe: (options?: RawAxiosRequestConfig) => Promise<RequestArgs>;
  /**
   *
   * @summary 自分自身が閲覧している小説リストを取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getViewedNovelsByMe: (
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
   * @param {UpdateUser} updateUser
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateUserByMe: (
    updateUser: UpdateUser,
    options?: RawAxiosRequestConfig,
  ) => Promise<RequestArgs>;
};
/**
 * UsersApi - functional programming interface
 * @export
 */
export declare const UsersApiFp: (configuration?: Configuration) => {
  /**
   *
   * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteUserByMe(
    options?: RawAxiosRequestConfig,
  ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>>;
  /**
   *
   * @summary ユーザーが投稿している小説リストを取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelsByUserId(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<
    (
      axios?: AxiosInstance,
      basePath?: string,
    ) => AxiosPromise<Array<NovelListItem>>
  >;
  /**
   *
   * @summary IDで自分以外のユーザーアカウント情報を取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserById(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserByMe(
    options?: RawAxiosRequestConfig,
  ): Promise<
    (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewMeUser>
  >;
  /**
   *
   * @summary 自分自身が閲覧している小説リストを取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getViewedNovelsByMe(
    options?: RawAxiosRequestConfig,
  ): Promise<
    (
      axios?: AxiosInstance,
      basePath?: string,
    ) => AxiosPromise<Array<NovelListItem>>
  >;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
   * @param {UpdateUser} updateUser
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateUserByMe(
    updateUser: UpdateUser,
    options?: RawAxiosRequestConfig,
  ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>>;
};
/**
 * UsersApi - factory interface
 * @export
 */
export declare const UsersApiFactory: (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) => {
  /**
   *
   * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  deleteUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<void>;
  /**
   *
   * @summary ユーザーが投稿している小説リストを取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getNovelsByUserId(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<NovelListItem>>;
  /**
   *
   * @summary IDで自分以外のユーザーアカウント情報を取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserById(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<User>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<ViewMeUser>;
  /**
   *
   * @summary 自分自身が閲覧している小説リストを取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  getViewedNovelsByMe(
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<Array<NovelListItem>>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
   * @param {UpdateUser} updateUser
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   */
  updateUserByMe(
    updateUser: UpdateUser,
    options?: RawAxiosRequestConfig,
  ): AxiosPromise<User>;
};
/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export declare class UsersApi extends BaseAPI {
  /**
   *
   * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  deleteUserByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<void, any, {}> | null | undefined>;
  /**
   *
   * @summary ユーザーが投稿している小説リストを取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  getNovelsByUserId(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<NovelListItem[], any, {}>>;
  /**
   *
   * @summary IDで自分以外のユーザーアカウント情報を取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  getUserById(
    userId: number,
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<User, any, {}>>;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  getUserByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<
    import('axios').AxiosResponse<ViewMeUser, any, {}> | null | undefined
  >;
  /**
   *
   * @summary 自分自身が閲覧している小説リストを取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  getViewedNovelsByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<
    import('axios').AxiosResponse<NovelListItem[], any, {}> | null | undefined
  >;
  /**
   *
   * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
   * @param {UpdateUser} updateUser
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  updateUserByMe(
    updateUser: UpdateUser,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ): Promise<import('axios').AxiosResponse<User, any, {}> | null | undefined>;
}
