/* tslint:disable */
/* eslint-disable */
/**
 * Conovel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, BaseAPI, operationServerMap } from './base';
import { withAuth } from './functional'; // 認証を一緒に実行（手動で追加）

// リフレッシュを実行（手動で追加）
export const createRefreshTokenRequest = (
  configuration: Configuration | undefined,
  axios: AxiosInstance,
  basePath: string,
  options?: RawAxiosRequestConfig,
) => {
  if (!configuration) {
    throw new Error('Configuration is required');
  }
  return () =>
    AuthApiFp(configuration)
      .refreshToken(options)
      .then((request) => request(axios, basePath));
};

/**
 *
 * @export
 * @interface ConflictSentence
 */
export interface ConflictSentence {
  /**
   *
   * @type {ErrorResponseError}
   * @memberof ConflictSentence
   */
  error?: ErrorResponseError;
  /**
   *
   * @type {Sentence}
   * @memberof ConflictSentence
   */
  main?: Sentence;
  /**
   *
   * @type {Sentence}
   * @memberof ConflictSentence
   */
  parent?: Sentence;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ConflictSentence
   */
  parallels?: Array<Sentence>;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ConflictSentence
   */
  children?: Array<Sentence>;
}
/**
 *
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
  /**
   *
   * @type {ErrorResponseError}
   * @memberof ErrorResponse
   */
  error?: ErrorResponseError;
}
/**
 *
 * @export
 * @interface ErrorResponseError
 */
export interface ErrorResponseError {
  /**
   * エラーコード
   * @type {number}
   * @memberof ErrorResponseError
   */
  code?: number;
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof ErrorResponseError
   */
  message?: string;
}
/**
 *
 * @export
 * @interface EvaluateSentence
 */
export interface EvaluateSentence {
  /**
   * 評価対象の投稿のID
   * @type {number}
   * @memberof EvaluateSentence
   */
  sentenceId?: number;
  /**
   * 評価の種類
   * @type {string}
   * @memberof EvaluateSentence
   */
  evaluation?: EvaluateSentenceEvaluationEnum;
}

export const EvaluateSentenceEvaluationEnum = {
  Good: 'good',
  Bad: 'bad',
  Stay: 'stay',
} as const;

export type EvaluateSentenceEvaluationEnum =
  (typeof EvaluateSentenceEvaluationEnum)[keyof typeof EvaluateSentenceEvaluationEnum];

/**
 *
 * @export
 * @interface NovelDetail
 */
export interface NovelDetail {
  /**
   * 小説の一意のid（この値は他の小説と重複しない必要があります）
   * @type {number}
   * @memberof NovelDetail
   */
  titleId?: number;
  /**
   * 小説のタイトル
   * @type {string}
   * @memberof NovelDetail
   */
  title?: string;
  /**
   * 名言・印象に残るシーン
   * @type {string}
   * @memberof NovelDetail
   */
  famousSentenceText?: string;
  /**
   * 小説の作者のid
   * @type {number}
   * @memberof NovelDetail
   */
  authorUserId?: number;
  /**
   * 小説の作者のペンネーム
   * @type {string}
   * @memberof NovelDetail
   */
  authorUserName?: string;
  /**
   * 小説の作者のアイコン画像のurl
   * @type {string}
   * @memberof NovelDetail
   */
  profileIconImage?: string;
  /**
   * 小説のジャンル
   * @type {Array<string>}
   * @memberof NovelDetail
   */
  titleGenres?: Array<string>;
  /**
   * 新着小説かどうか
   * @type {boolean}
   * @memberof NovelDetail
   */
  isNew?: boolean;
  /**
   * 人気小説かどうか
   * @type {boolean}
   * @memberof NovelDetail
   */
  isFamous?: boolean;
  /**
   * 小説の閲覧数
   * @type {number}
   * @memberof NovelDetail
   */
  viewCount?: number;
  /**
   * 小説のGood評価の数
   * @type {number}
   * @memberof NovelDetail
   */
  evaluationGoodCount?: number;
  /**
   * 小説の作成日時
   * @type {string}
   * @memberof NovelDetail
   */
  createdAt?: string;
  /**
   * 小説の修正日時
   * @type {string}
   * @memberof NovelDetail
   */
  updatedAt?: string;
  /**
   * 小説の紹介文
   * @type {string}
   * @memberof NovelDetail
   */
  mainCopy?: string;
  /**
   * 小説に投稿している投稿者の数
   * @type {number}
   * @memberof NovelDetail
   */
  sentenceUserCount?: number;
  /**
   * 小説に投稿された投稿の階層数
   * @type {number}
   * @memberof NovelDetail
   */
  sentenceHierarchyCount?: number;
  /**
   * 小説を読んだユーザーの数
   * @type {number}
   * @memberof NovelDetail
   */
  readerCount?: number;
  /**
   * 小説のあらすじ
   * @type {string}
   * @memberof NovelDetail
   */
  overview?: string;
}
/**
 *
 * @export
 * @interface NovelListItem
 */
export interface NovelListItem {
  /**
   * 小説の一意のid（この値は他の小説と重複しない必要があります）
   * @type {number}
   * @memberof NovelListItem
   */
  titleId?: number;
  /**
   * 小説のタイトル
   * @type {string}
   * @memberof NovelListItem
   */
  title?: string;
  /**
   * 名言・印象に残るシーン
   * @type {string}
   * @memberof NovelListItem
   */
  famousSentenceText?: string;
  /**
   * 小説の作者のid
   * @type {number}
   * @memberof NovelListItem
   */
  authorUserId?: number;
  /**
   * 小説の作者のペンネーム
   * @type {string}
   * @memberof NovelListItem
   */
  authorUserName?: string;
  /**
   * 小説の作者のアイコン画像のurl
   * @type {string}
   * @memberof NovelListItem
   */
  profileIconImage?: string;
  /**
   * 小説のジャンル
   * @type {Array<string>}
   * @memberof NovelListItem
   */
  titleGenres?: Array<string>;
  /**
   * 新着小説かどうか
   * @type {boolean}
   * @memberof NovelListItem
   */
  isNew?: boolean;
  /**
   * 人気小説かどうか
   * @type {boolean}
   * @memberof NovelListItem
   */
  isFamous?: boolean;
  /**
   * 小説の閲覧数
   * @type {number}
   * @memberof NovelListItem
   */
  viewCount?: number;
  /**
   * 小説のGood評価の数
   * @type {number}
   * @memberof NovelListItem
   */
  evaluationGoodCount?: number;
  /**
   * 小説の作成日時
   * @type {string}
   * @memberof NovelListItem
   */
  createdAt?: string;
  /**
   * 小説の修正日時
   * @type {string}
   * @memberof NovelListItem
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface PostSentence
 */
export interface PostSentence {
  /**
   * 親投稿のid
   * @type {number}
   * @memberof PostSentence
   */
  parentSentenceId?: number;
  /**
   * 親投稿の修正日時(投稿中の親投稿の更新有無を確認するため)
   * @type {string}
   * @memberof PostSentence
   */
  parentUpdatedAt?: string;
  /**
   * 新投稿の本文テキスト
   * @type {string}
   * @memberof PostSentence
   */
  sentence?: string;
}
/**
 *
 * @export
 * @interface Sentence
 */
export interface Sentence {
  /**
   * 投稿の一意のid（この値は他の投稿と重複しない必要があります）
   * @type {number}
   * @memberof Sentence
   */
  sentenceId?: number;
  /**
   * 投稿の本文テキスト
   * @type {string}
   * @memberof Sentence
   */
  sentence?: string;
  /**
   * 投稿ユーザーのid
   * @type {number}
   * @memberof Sentence
   */
  sentenceUserId?: number;
  /**
   * 投稿ユーザーのペンネーム
   * @type {string}
   * @memberof Sentence
   */
  sentenceUserName?: string;
  /**
   * 投稿ユーザーアイコン画像のurl
   * @type {string}
   * @memberof Sentence
   */
  profileIconImage?: string;
  /**
   * 投稿に対するGood評価の数
   * @type {number}
   * @memberof Sentence
   */
  evaluationGoodCount?: number;
  /**
   * 投稿に対するStay評価の数
   * @type {number}
   * @memberof Sentence
   */
  evaluationStayCount?: number;
  /**
   * 投稿日時
   * @type {string}
   * @memberof Sentence
   */
  createdAt?: string;
  /**
   * 修正日時
   * @type {string}
   * @memberof Sentence
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
  /**
   * ユーザーのペンネーム
   * @type {string}
   * @memberof UpdateUser
   */
  userName?: string;
  /**
   * ユーザーのニックネーム
   * @type {string}
   * @memberof UpdateUser
   */
  nickName?: string;
  /**
   * 匿名設定
   * @type {boolean}
   * @memberof UpdateUser
   */
  isAnonymous?: boolean;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof UpdateUser
   */
  profileIconImage?: string;
}
/**
 *
 * @export
 * @interface User
 */
export interface User {
  /**
   * ユーザーの一意のid
   * @type {number}
   * @memberof User
   */
  userId?: number;
  /**
   * ユーザーのペンネーム
   * @type {string}
   * @memberof User
   */
  userName?: string;
  /**
   * ユーザーのニックネーム
   * @type {string}
   * @memberof User
   */
  nickName?: string;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof User
   */
  profileIconImage?: string;
  /**
   * Good評価の数
   * @type {number}
   * @memberof User
   */
  evaluationGoodCount?: number;
  /**
   * ユーザーの作成日時
   * @type {string}
   * @memberof User
   */
  createdAt?: string;
  /**
   * ユーザーの修正日時
   * @type {string}
   * @memberof User
   */
  updatedAt?: string;
}
/**
 *
 * @export
 * @interface ViewEvaluation
 */
export interface ViewEvaluation {
  /**
   * 評価対象の投稿のID
   * @type {number}
   * @memberof ViewEvaluation
   */
  sentenceId?: number;
  /**
   * Good評価の数
   * @type {number}
   * @memberof ViewEvaluation
   */
  evaluationGoodCount?: number;
  /**
   * Stay評価の数
   * @type {number}
   * @memberof ViewEvaluation
   */
  evaluationStayCount?: number;
}
/**
 *
 * @export
 * @interface ViewMeUser
 */
export interface ViewMeUser {
  /**
   * ユーザーの一意のid
   * @type {number}
   * @memberof ViewMeUser
   */
  userId?: number;
  /**
   * ユーザーのペンネーム
   * @type {string}
   * @memberof ViewMeUser
   */
  userName?: string;
  /**
   * ユーザーのニックネーム
   * @type {string}
   * @memberof ViewMeUser
   */
  nickName?: string;
  /**
   * ユーザーアイコン画像のurl
   * @type {string}
   * @memberof ViewMeUser
   */
  profileIconImage?: string;
  /**
   * Good評価の数
   * @type {number}
   * @memberof ViewMeUser
   */
  evaluationGoodCount?: number;
  /**
   * ユーザーの作成日時
   * @type {string}
   * @memberof ViewMeUser
   */
  createdAt?: string;
  /**
   * ユーザーの修正日時
   * @type {string}
   * @memberof ViewMeUser
   */
  updatedAt?: string;
  /**
   * ユーザーの生年月（YYYY/MM）
   * @type {string}
   * @memberof ViewMeUser
   */
  birthYearAndMonth?: string;
  /**
   * 匿名設定
   * @type {boolean}
   * @memberof ViewMeUser
   */
  isAnonymous?: boolean;
}
/**
 *
 * @export
 * @interface ViewSentence
 */
export interface ViewSentence {
  /**
   *
   * @type {Sentence}
   * @memberof ViewSentence
   */
  main?: Sentence;
  /**
   *
   * @type {Sentence}
   * @memberof ViewSentence
   */
  parent?: Sentence;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ViewSentence
   */
  parallels?: Array<Sentence>;
  /**
   *
   * @type {Array<Sentence>}
   * @memberof ViewSentence
   */
  children?: Array<Sentence>;
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logOut: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/auth/logout`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary トークンのリフレッシュ（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshToken: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/auth/refresh`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async logOut(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.logOut(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.logOut']?.[localVarOperationServerIndex]
          ?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary トークンのリフレッシュ（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async refreshToken(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.refreshToken({
        ...options,
        withCredentials: true,
      }); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.refreshToken']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = AuthApiFp(configuration);
  return {
    /**
     *
     * @summary ログアウト
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    logOut(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp
        .logOut(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary トークンのリフレッシュ（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    refreshToken(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp
        .refreshToken(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
  /**
   *
   * @summary ログアウト
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public logOut(options?: RawAxiosRequestConfig) {
    return AuthApiFp(this.configuration)
      .logOut(options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary トークンのリフレッシュ（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public refreshToken(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      AuthApiFp(this.configuration)
        .refreshToken(options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }
}

/**
 * EvaluationsApi - axios parameter creator
 * @export
 */
export const EvaluationsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary 投稿に対する評価を追加（認証あり）
     * @param {EvaluateSentence} evaluateSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    evaluateSentence: async (
      evaluateSentence: EvaluateSentence,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'evaluateSentence' is not null or undefined
      assertParamExists(
        'evaluateSentence',
        'evaluateSentence',
        evaluateSentence,
      );
      const localVarPath = `/evaluations`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        evaluateSentence,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * EvaluationsApi - functional programming interface
 * @export
 */
export const EvaluationsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    EvaluationsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary 投稿に対する評価を追加（認証あり）
     * @param {EvaluateSentence} evaluateSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async evaluateSentence(
      evaluateSentence: EvaluateSentence,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewEvaluation>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.evaluateSentence(evaluateSentence, {
          ...options,
          withCredentials: true,
        }); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['EvaluationsApi.evaluateSentence']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * EvaluationsApi - factory interface
 * @export
 */
export const EvaluationsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = EvaluationsApiFp(configuration);
  return {
    /**
     *
     * @summary 投稿に対する評価を追加（認証あり）
     * @param {EvaluateSentence} evaluateSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    evaluateSentence(
      evaluateSentence: EvaluateSentence,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ViewEvaluation> {
      return localVarFp
        .evaluateSentence(evaluateSentence, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * EvaluationsApi - object-oriented interface
 * @export
 * @class EvaluationsApi
 * @extends {BaseAPI}
 */
export class EvaluationsApi extends BaseAPI {
  /**
   *
   * @summary 投稿に対する評価を追加（認証あり）
   * @param {EvaluateSentence} evaluateSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof EvaluationsApi
   */
  public evaluateSentence(
    evaluateSentence: EvaluateSentence,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      EvaluationsApiFp(this.configuration)
        .evaluateSentence(evaluateSentence, options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }
}

/**
 * NovelsApi - axios parameter creator
 * @export
 */
export const NovelsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary IDで小説の概要を取得
     * @param {number} titleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovelById: async (
      titleId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'titleId' is not null or undefined
      assertParamExists('getNovelById', 'titleId', titleId);
      const localVarPath = `/novels/{titleId}`.replace(
        `{${'titleId'}}`,
        encodeURIComponent(String(titleId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 小説リストを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovels: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/novels`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * NovelsApi - functional programming interface
 * @export
 */
export const NovelsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = NovelsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary IDで小説の概要を取得
     * @param {number} titleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getNovelById(
      titleId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<NovelDetail>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getNovelById(
        titleId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['NovelsApi.getNovelById']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 小説リストを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getNovels(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<NovelListItem>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getNovels(options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['NovelsApi.getNovels']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * NovelsApi - factory interface
 * @export
 */
export const NovelsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = NovelsApiFp(configuration);
  return {
    /**
     *
     * @summary IDで小説の概要を取得
     * @param {number} titleId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovelById(
      titleId: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<NovelDetail> {
      return localVarFp
        .getNovelById(titleId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 小説リストを取得
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovels(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<NovelListItem>> {
      return localVarFp
        .getNovels(options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * NovelsApi - object-oriented interface
 * @export
 * @class NovelsApi
 * @extends {BaseAPI}
 */
export class NovelsApi extends BaseAPI {
  /**
   *
   * @summary IDで小説の概要を取得
   * @param {number} titleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NovelsApi
   */
  public getNovelById(titleId: number, options?: RawAxiosRequestConfig) {
    return NovelsApiFp(this.configuration)
      .getNovelById(titleId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 小説リストを取得
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof NovelsApi
   */
  public getNovels(options?: RawAxiosRequestConfig) {
    return NovelsApiFp(this.configuration)
      .getNovels(options)
      .then((request) => request(this.axios, this.basePath));
  }
}

/**
 * SentencesApi - axios parameter creator
 * @export
 */
export const SentencesApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary IDで投稿を取得（認証あり）
     * @param {number} sentenceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSentenceById: async (
      sentenceId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'sentenceId' is not null or undefined
      assertParamExists('getSentenceById', 'sentenceId', sentenceId);
      const localVarPath = `/sentences/{sentenceId}`.replace(
        `{${'sentenceId'}}`,
        encodeURIComponent(String(sentenceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary メイン投稿の続きの新規投稿を作成（認証あり）
     * @param {PostSentence} postSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postSentence: async (
      postSentence: PostSentence,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'postSentence' is not null or undefined
      assertParamExists('postSentence', 'postSentence', postSentence);
      const localVarPath = `/sentences`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        postSentence,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * SentencesApi - functional programming interface
 * @export
 */
export const SentencesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    SentencesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary IDで投稿を取得（認証あり）
     * @param {number} sentenceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getSentenceById(
      sentenceId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getSentenceById(
        sentenceId,
        {
          ...options,
          withCredentials: true,
        },
      ); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SentencesApi.getSentenceById']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary メイン投稿の続きの新規投稿を作成（認証あり）
     * @param {PostSentence} postSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async postSentence(
      postSentence: PostSentence,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewSentence>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.postSentence(
        postSentence,
        {
          ...options,
          withCredentials: true,
        },
      ); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['SentencesApi.postSentence']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * SentencesApi - factory interface
 * @export
 */
export const SentencesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = SentencesApiFp(configuration);
  return {
    /**
     *
     * @summary IDで投稿を取得（認証あり）
     * @param {number} sentenceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getSentenceById(
      sentenceId: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ViewSentence> {
      return localVarFp
        .getSentenceById(sentenceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary メイン投稿の続きの新規投稿を作成（認証あり）
     * @param {PostSentence} postSentence
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    postSentence(
      postSentence: PostSentence,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ViewSentence> {
      return localVarFp
        .postSentence(postSentence, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * SentencesApi - object-oriented interface
 * @export
 * @class SentencesApi
 * @extends {BaseAPI}
 */
export class SentencesApi extends BaseAPI {
  /**
   *
   * @summary IDで投稿を取得（認証あり）
   * @param {number} sentenceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SentencesApi
   */
  public getSentenceById(
    sentenceId: number,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      SentencesApiFp(this.configuration)
        .getSentenceById(sentenceId, options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }

  /**
   *
   * @summary メイン投稿の続きの新規投稿を作成（認証あり）
   * @param {PostSentence} postSentence
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof SentencesApi
   */
  public postSentence(
    postSentence: PostSentence,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      SentencesApiFp(this.configuration)
        .postSentence(postSentence, options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }
}

/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUserByMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/users/me/delete`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary ユーザーが投稿している小説リストを取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovelsByUserId: async (
      userId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('getNovelsByUserId', 'userId', userId);
      const localVarPath = `/users/{userId}/postedNovels`.replace(
        `{${'userId'}}`,
        encodeURIComponent(String(userId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary IDで自分以外のユーザーアカウント情報を取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserById: async (
      userId: number,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'userId' is not null or undefined
      assertParamExists('getUserById', 'userId', userId);
      const localVarPath = `/users/{userId}`.replace(
        `{${'userId'}}`,
        encodeURIComponent(String(userId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserByMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/users/me`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 自分自身が閲覧している小説リストを取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getViewedNovelsByMe: async (
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/users/me/viewedNovels`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
     * @param {UpdateUser} updateUser
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateUserByMe: async (
      updateUser: UpdateUser,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'updateUser' is not null or undefined
      assertParamExists('updateUserByMe', 'updateUser', updateUser);
      const localVarPath = `/users/me/update`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateUser,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteUserByMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUserByMe({
        ...options,
        withCredentials: true,
      }); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.deleteUserByMe']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary ユーザーが投稿している小説リストを取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getNovelsByUserId(
      userId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<NovelListItem>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getNovelsByUserId(userId, options);
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.getNovelsByUserId']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary IDで自分以外のユーザーアカウント情報を取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getUserById(
      userId: number,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUserById(
        userId,
        options,
      );
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.getUserById']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getUserByMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<ViewMeUser>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getUserByMe({
        ...options,
        withCredentials: true,
      }); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.getUserByMe']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 自分自身が閲覧している小説リストを取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getViewedNovelsByMe(
      options?: RawAxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<NovelListItem>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.getViewedNovelsByMe({
          ...options,
          withCredentials: true,
        }); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.getViewedNovelsByMe']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
     * @param {UpdateUser} updateUser
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateUserByMe(
      updateUser: UpdateUser,
      options?: RawAxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserByMe(
        updateUser,
        {
          ...options,
          withCredentials: true,
        },
      ); // 認証時にクッキーを送る（手動で修正）
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
      const localVarOperationServerBasePath =
        operationServerMap['UsersApi.updateUserByMe']?.[
          localVarOperationServerIndex
        ]?.url;
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath);
    },
  };
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = UsersApiFp(configuration);
  return {
    /**
     *
     * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<void> {
      return localVarFp
        .deleteUserByMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary ユーザーが投稿している小説リストを取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNovelsByUserId(
      userId: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<NovelListItem>> {
      return localVarFp
        .getNovelsByUserId(userId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary IDで自分以外のユーザーアカウント情報を取得
     * @param {number} userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserById(
      userId: number,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<User> {
      return localVarFp
        .getUserById(userId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUserByMe(options?: RawAxiosRequestConfig): AxiosPromise<ViewMeUser> {
      return localVarFp
        .getUserByMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 自分自身が閲覧している小説リストを取得（認証あり）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getViewedNovelsByMe(
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<NovelListItem>> {
      return localVarFp
        .getViewedNovelsByMe(options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
     * @param {UpdateUser} updateUser
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateUserByMe(
      updateUser: UpdateUser,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<User> {
      return localVarFp
        .updateUserByMe(updateUser, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
  /**
   *
   * @summary 自分自身のユーザーアカウントを論理削除（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public deleteUserByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      UsersApiFp(this.configuration)
        .deleteUserByMe(options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }

  /**
   *
   * @summary ユーザーが投稿している小説リストを取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public getNovelsByUserId(userId: number, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .getNovelsByUserId(userId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary IDで自分以外のユーザーアカウント情報を取得
   * @param {number} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public getUserById(userId: number, options?: RawAxiosRequestConfig) {
    return UsersApiFp(this.configuration)
      .getUserById(userId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @summary 自分自身のユーザーアカウント情報を取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public getUserByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      UsersApiFp(this.configuration)
        .getUserByMe(options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }

  /**
   *
   * @summary 自分自身が閲覧している小説リストを取得（認証あり）
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public getViewedNovelsByMe(
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      UsersApiFp(this.configuration)
        .getViewedNovelsByMe(options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }

  /**
   *
   * @summary 自分自身のユーザーアカウント情報を更新（認証あり）
   * @param {UpdateUser} updateUser
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsersApi
   */
  public updateUserByMe(
    updateUser: UpdateUser,
    onFailure?: () => Promise<void>, // 認証失敗時の処理（手動で修正）
    options?: RawAxiosRequestConfig,
  ) {
    // withAuthを一緒に実行（手動で修正）
    const f = () =>
      UsersApiFp(this.configuration)
        .updateUserByMe(updateUser, options)
        .then((request) => request(this.axios, this.basePath));
    const r = createRefreshTokenRequest(
      this.configuration,
      this.axios,
      this.basePath,
      options,
    );
    return withAuth(f, r, onFailure ?? (() => Promise.resolve()));
  }
}
